language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

sudo: false

before_script:
  - composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - composer outdated -D --strict
  - composer require phpunit/phpunit --dev
  - composer require phpstan/phpstan --dev
  - composer require squizlabs/php_codesniffer --dev
  - vendor/bin/phpstan analyze src tests --level=max
  - vendor/bin/phpcs src tests --standard=PSR2 -n
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover